name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.23'
          tools: composer:1.10.24
      - name: Test
        run: Resources/Private/Build/test.sh
